=== sanchit1053/nextNextFlow/workflow.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

 <xs:simpleType name="globalType" final="restriction" >
    <xs:restriction base="xs:string">
        <xs:enumeration value="none"/>
        <xs:enumeration value="in"/>
        <xs:enumeration value="out"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="channelType">
    <xs:sequence>
        <xs:element name="input" type="xs:string" minOccurs="0"/>
        <xs:element name="output" type="xs:string" minOccurs="0"/>
        <xs:element name="global" type="globalType" minOccurs="0"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="processType">
    <xs:sequence>
        <xs:element name="input" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="output" type="xs:string" minOccurs="0"/>
        <xs:element name="command" type="xs:string"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="workflowType">
    <xs:sequence>
        <xs:element name="channel" type="channelType" minOccurs="0" maxOccurs="unbounded"/>
        <xs:element name="process" type="processType" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:element name="workflow" type="workflowType"/>

</xs:schema>

=== sanchit1053/nextNextFlow/test_container9.xml
<?xml version="1.0" encoding="UTF-8"?>

<workflow
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="workflow.xsd">

<channel name="c1">
    <global>in</global>
	<init>3</init>
</channel>
<channel name="c2"/>
<channel name="c3">
    <global>out</global>
</channel>
<channel name="c4"/>
<channel name="c5"/>
<mux name="m1">
    <input>c1</input>
    <input>c5</input>
    <output>c2</output>
</mux>
<process name="p1">
    <input>c2</input>
    <output>c3</output>
    <output>c4</output>
    <script>scripts/9.1.sh</script>
</process>
<process name="p2">
    <input>c4</input>
    <output>c5</output>
    <script>scripts/9.2.sh</script>
</process>

</workflow>

=== sanchit1053/nextNextFlow/test_container4.xml
<?xml version="1.0" encoding="UTF-8"?>

<workflow
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="workflow.xsd">

<channel name="c1">
    <global>in</global>
</channel>
<channel name="c2"/>
<channel name="c3"/>
<channel name="c4"/>
<channel name="c5"/>
<channel name="c6">
    <global>out</global>
</channel>
<mux name="m1">
    <input>c1</input>
    <output>c2</output>
    <output>c3</output>
</mux>
<mux name="m2">
    <input>c4</input>
    <input>c5</input>
    <output>c6</output>
</mux>
<process name="p1">
    <input>c2</input>
    <output>c4</output>
    <command>#!/bin/sh&#xA;sleep 1&#xA;cat c2  | cut -c -6 &gt; c4</command>
</process>
<process name="p2">
    <input>c3</input>
    <output>c5</output>
    <command>#!/bin/sh&#xA;sleep 1&#xA;cat c3  | cut -c 2- &gt; c5</command>
</process>

</workflow>

=== sanchit1053/nextNextFlow/test_container2.xml
<?xml version="1.0" encoding="UTF-8"?>

<workflow
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="workflow.xsd">

<channel name="c1">
    <global>in</global>
	<init> C1 Value </init>
</channel>
<channel name="c2"/>
<channel name="c3">
    <global>out</global>
</channel>
<process name="p1">
    <input>c1</input>
    <output>c2</output>
    <command>#!/bin/sh&#xA;sleep 1&#xA;cat c1  | cut -c -6 &gt; c2</command>
</process>
<process name="p2">
    <input>c2</input>
    <output>c3</output>
    <command>#!/bin/sh&#xA;sleep 1&#xA;cat c2  | cut -c 2- &gt; c3</command>
</process>

</workflow>

=== sanchit1053/nextNextFlow/test_container.xml
<?xml version="1.0" encoding="UTF-8"?>

<workflow
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="workflow.xsd">

<channel name="c1">
    <global>in</global>
	<init> Value in c1 </init>
</channel>
<channel name="c3">
    <global>in</global>
	<init> Value in c3 </init>
</channel>
<channel name="c2">
    <global>out</global>
</channel>
<process name="p1">
    <input>c1</input>
    <input>c3</input>
    <output>c2</output>
    <command>#!/bin/sh&#xA;sleep 1&#xA;cat c1&#xA;cat c1 &gt; c2&#xA;cat c3&#xA;cat c3 &gt;&gt; c2</command>
</process>

</workflow>

=== sanchit1053/nextNextFlow/test_container10.xml
<?xml version="1.0" encoding="UTF-8"?>

<workflow
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="workflow.xsd">

<channel name="c1"/>
<channel name="c2">
    <global>out</global>
</channel>
<process name="p1">
    <output>c1</output>
    <script>scripts/10.1.sh</script>
</process>
<process name="p2">
    <input>c1</input>
    <output>c2</output>
    <script>scripts/10.2.sh</script>
</process>

</workflow>

=== sanchit1053/nextNextFlow/test_container6.xml
<?xml version="1.0" encoding="UTF-8"?>

<workflow
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:noNamespaceSchemaLocation="workflow.xsd">

<channel name="c1">
    <global>in</global>
	<init>some data</init>
</channel>
<channel name="c2"/>
<channel name="c3"/>
<channel name="c4">
    <global>out</global>
</channel>
<mux name="m1">
    <input>c2</input>
    <input>c3</input>
    <output>c4</output>
</mux>
<process name="p1">
    <input>c1</input>
    <output>c2</output>
    <output>c3</output>
    <script>scripts/6.1.sh</script>
</process>

</workflow>
